#!/usr/bin/env ruby
require_relative 'flash-chip-proxy'

port = 80
original_host = ARGV[0]
cache_directory = ARGV[1]
proxy = FlashChipProxy.new(cache_directory, port)
proxy.learn_from(original_host, port)
proxy.thread().join()
